### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by zhangkai803** [mkxml/vscode-filesize#51] opened 2024-10-31 09:14 UTC
I have used `filesize` extension for many years. However, i ran into a trouble with high cpu usage when using vscode recently.
I disabled all extionsions i have installed and enable them one by one, i finally found out that when i enable this extension, a process called `Code Helper (Plugin)` kept running after everytime i reload the window, and 100% cpu usage was eaten by them.

My environ:

```
MacOS 15.0.1 (24A348)

Version: 1.95.0 (Universal)
Commit: 912bb683695358a54ae0c670461738984cbb5b95
Date: 2024-10-28T20:16:24.561Z (2 days ago)
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.0.0
```

**Comment by roxizhauk** [comment] 2024-11-01 01:39
Same here

**Comment by mkxml** [comment] 2024-11-01 18:05
Yes, I'm reproducing this as well, strange bug that only happens after a window reload as you said.

I will look into this together with other issues, should have a new release soon.

**Comment by mkxml** [comment] 2024-11-01 20:24
@zhangkai803 I released version `3.2.1` today, but I think the problem continues, I'll further investigate this.

**Comment by jamiolee** [comment] 2024-11-02 02:46
+1 Encountered the same problem following a recent update to this extension. Both my local machine and all remote VS Code sessions experienced 100% CPU utilization spikes, attributed to a node process. Uninstalling the extension and restarting the servers successfully resolved the issue.

**Comment by zhangkai803** [comment] 2024-11-04 06:46
> @zhangkai803 I released version `3.2.1` today, but I think the problem continues, I'll further investigate this.

Thanks for your time. I have tested version `3.2.1` on my machine and yes, this problem still exists.

**Comment by zhangvj** [comment] 2024-11-06 01:49
Same here！！！！

**Comment by habibium** [comment] 2024-11-08 09:46
+1

**Comment by RZAlucard** [comment] 2024-11-09 11:47
Same here！！！！
I have over 200 plugins installed, it's such a pain
T^T

**Comment by spktkl** [comment] 2024-11-10 05:15
Same issue here. I reinstalled all extensions one at a time, and uninstalled and reinstalled vscode-filesize to confirm it's the one.

Here's details in case it's helpful for debugging. 

## System

M3 Macbook Air
MacOS 15.1

### VSC

Version: 1.95.2
Commit: e8653663e8840adaf45af01eab5c627a5af81807
Date: 2024-11-07T11:07:22.054Z (2 days ago)
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.1.0

### vscode-filesize

v3.2.1

## Steps to reproduce

1. Open Process Explorer to monitor extensionHost
2. Install vscode-filesize
3. Trigger a window load (Reload Window is simplest)

### Expected
Old extensionHost exits when it is replaced by the new extensionHost process

### Actual behavior
On every window load (manually reloading, opening a new workspace or folder, switching profiles), the old extensionHost process remains, ramping up to 99-100% CPU usage and remaining there until VSC is quit. Repeated window loads cause another extensionHost process to be added each time, using an additional 100% of CPU. The processes continue indefinitely until VSC is quit and relaunched entirely. VSC also takes significantly longer to quit when this problem is occurring.

## Logs

Extension Host log (viewed with (Developer: Show Logs...' command) with vscode-filesize installed:

```txt
2024-11-09 20:38:08.381 [info] Extension host with pid 97510 started
2024-11-09 20:38:08.402 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2024-11-09 20:38:08.410 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2024-11-09 20:38:08.445 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2024-11-09 20:38:08.447 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2024-11-09 20:38:08.472 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2024-11-09 20:38:08.554 [info] Eager extensions activated
2024-11-09 20:38:08.582 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2024-11-09 20:38:08.583 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2024-11-09 20:38:08.892 [info] ExtensionService#_doActivateExtension vscode.configuration-editing, startup: false, activationEvent: 'onLanguage:jsonc'
2024-11-09 20:38:08.897 [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2024-11-09 20:38:08.918 [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2024-11-09 20:38:27.337 [info] ExtensionService#_doActivateExtension mkxml.vscode-filesize, startup: false, activationEvent: 'onStartupFinished'

>>>2024-11-09 20:38:47.088 [info] Extension host terminating: renderer closed the MessagePort<<<
>>>2024-11-09 20:38:47.629 [info] Extension host with pid 97712 started<<<

2024-11-09 20:38:47.644 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2024-11-09 20:38:47.667 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2024-11-09 20:38:47.764 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2024-11-09 20:38:47.793 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2024-11-09 20:38:47.840 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2024-11-09 20:38:47.891 [info] Eager extensions activated
2024-11-09 20:38:47.908 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2024-11-09 20:38:47.910 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2024-11-09 20:38:47.936 [info] ExtensionService#_doActivateExtension mkxml.vscode-filesize, startup: false, activationEvent: 'onStartupFinished'
```

Normally without vscode-filesize installed, the log contains these lines:

```txt
2024-11-09 20:40:11.485 [info] Extension host terminating: renderer closed the MessagePort
2024-11-09 20:40:11.497 [info] Extension host with pid 98143 exiting with code 0
2024-11-09 20:40:11.986 [info] Extension host with pid 98231 started
```

The logs suggest that vscode-filesize is causing the outgoing extensionHost to fail to exit when it's supposed to.

## Process details

I disabled all other extensions except for vscode-filesize, and in this context I only saw a total of 2 extensionHost processes (1 old, 1 new) accumulate. Repeated reloads no longer created new processes.

 The singular old extensionHost had a subprocess related to the JSON language server:

```txt
extensionHost [1]
CPU: 99
Memory: 164
PID: 5033
    /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=5033
    CPU: 0
    Memory: 66
    PID: 5076
```

I personally have no idea what extensionHost does or how it works, but it seems that the amount of extensionHosts spawned is dependent on the number of other extensions enabled? In the below screenshots, all extensions were enabled, and new extensionHosts kept spawning as many times as I reloaded; the extensionHosts similarly had subprocesses pointing to various extensions there.

### Initial launch of VSC with filesize installed

<img width="365" alt="image" src="https://github.com/user-attachments/assets/54261ea4-8ea7-4bdd-8f46-576fdd93966f">

### First reload

<img width="365" alt="image" src="https://github.com/user-attachments/assets/19e0d0b7-b53b-4cf7-9c12-389dbb225b04">

### Second reload

<img width="363" alt="image" src="https://github.com/user-attachments/assets/a5c20422-f720-4550-9cd5-b2359bdfed22">

**Comment by dapanghuzi** [comment] 2024-11-11 09:58
Same issue here.
It happened when New Window or Open Recent.

**Comment by mkxml** [comment] 2024-11-11 17:05
@spktkl thanks for the detailed info, looking into it!

**Comment by mkxml** [comment] 2024-11-11 17:05
Anyone reproduce this on Windows or Linux?

**Comment by mkxml** [comment] 2024-11-12 11:34
It's not fixed in `3.2.2` unfortunately, still trying to figure this out, I may need some help from the vscode team.  There is nothing in the code that should result in this.

It may be some change with vscode that is conflicting with the extension code.

**Comment by gjsjohnmurray** [comment] 2024-11-13 05:25
> Same here！！！！ I spent the whole day searching for this issue. I have too many extensions installed. T^T

Did you try using `Start Extension Bisect` from Command Palette? Or does this particular problem require a more comprehensive restart between steps?

**Comment by zhangvj** [comment] 2024-11-13 05:47
> > Same here！！！！ I spent the whole day searching for this issue. I have too many extensions installed. T^T
> 
> Did you try using `Start Extension Bisect` from Command Palette? Or does this particular problem require a more comprehensive restart between steps?

Yes, I tried, but it didn’t help much in identifying the issue. Strange bug that only happens after a window reload, even if you disable all extensions

**Comment by piengeng** [comment] 2024-11-13 06:11
> Anyone reproduce this on Windows or Linux?

yes, seen on linux.

**Comment by mkxml** [comment] 2024-11-22 18:14
> > > Same here！！！！ I spent the whole day searching for this issue. I have too many extensions installed. T^T
> > 
> > 
> > Did you try using `Start Extension Bisect` from Command Palette? Or does this particular problem require a more comprehensive restart between steps?
> 
> Yes, I tried, but it didn’t help much in identifying the issue. Strange bug that only happens after a window reload, even if you disable all extensions

@zhangvj Did you try disabling copilot?

Wasn't able to reproduce this after disabling copilot.

**Comment by mkxml** [comment] 2024-11-22 18:20
After checking [this post](https://github.com/microsoft/vscode/issues/232699#issuecomment-2488974584) I see the vscode team released `1.95.3` that seems to fix the issue, I'm not reproducing it anymore on my env.

Please update vscode to `1.95.3` and check. If more people confirm this, I will close this issue.

**Comment by habibium** [comment] 2024-11-24 12:54
> After checking [this post](https://github.com/microsoft/vscode/issues/232699#issuecomment-2488974584) I see the vscode team released `1.95.3` that seems to fix the issue, I'm not reproducing it anymore on my env.
> 
> Please update vscode to `1.95.3` and check. If more people confirm this, I will close this issue.

Met too. Can't reproduce this issue anymore in `1.95.3`.

**Comment by zhangkai803** [comment] 2024-11-25 10:17
Not reproducing this problem anymore in `Version: 1.95.3 (Universal)`.

**Comment by mkxml** [comment] 2024-11-25 16:25
Closing it now, if we see this problem reappearing in the future we can reopen this.

**Closed by mkxml** 2024-11-25 16:25 UTC
Labels: bug
